---
# tasks/validate-disks.yml
- name: Gather disk information
  command: lsblk -o NAME,SERIAL,LABEL,VENDOR,MODEL,FSTYPE,SIZE -J
  register: lsblk_output
  changed_when: false

- name: Set disk facts
  set_fact:
    disks_info: >-
      {{ lsblk_output.stdout | from_json | json_query('blockdevices[*].{name: name, serial: serial, label: label, vendor: vendor, model: model, fstype: fstype, size: size}') | selectattr('serial', 'defined') | list }}

- name: Debug disk information
  debug:
    var: disks_info

- name: Check for serial mismatches
  block:
    - name: Find disks with mismatched serials
      set_fact:
        mismatched_disks: >-
          {{ luks_disks | selectattr('serial', 'in', disks_info | map(attribute='serial') | list)
             | rejectattr('serial', 'in', disks_info | selectattr('serial', 'in', luks_disks | map(attribute='serial') | list)
                  | map(attribute='serial') | list) 
             | list }}

    - name: Alert on mismatched disks
      fail:
        msg: |
          Disk configuration mismatch detected:
          {% for disk in mismatched_disks %}
          - Device: {{ disk.device }}
            Expected Serial: {{ disk.serial }}
            Available Serials: {{ disks_info | map(attribute='serial') | list }}
          {% endfor %}
      when: mismatched_disks | length > 0